# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: m-ibot.eu
title: m-ibot.eu

#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This website provides information about ##NAME## and his projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m-ibot.eu"
github_username: m-ibot

remote_theme: mmistakes/minimal-mistakes@4.24.0

# Theme specific configurations, see https://mmistakes.github.io/minimal-mistakes/docs/configuration/
minimal_mistakes_skin: dark
locale: "en"
title_separator: "#"
subtitle: Me and my projects
name: "##NAME##"
repository: m-ibot/m-ibot.github.io
logo: /assets/images/m-ibot-logo.png
og_image: /assets/images/m-ibot-logo.png
breadcrumbs: true
date_format: "%d-%m-%Y"
read_time: true
# search did not show any results. enable once it's fixed.
search: false
timezone: Europe/Berlin
google_site_verification: "##SEO_GOOGLE##"
bing_site_verification: "##SEO_BING##"

lunr:
  search_within_pages: true

social:
  type: Person
  links:
    - "##SOCIAL_XING##"
    - "##SOCIAL_LINKEDIN##"

author:
  name: "##NAME##"
  avatar: "/assets/images/profile.jpeg"
  bio: "Software Engineer"
  location: "Hamburg, Germany"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "##SOCIAL_LINKEDIN##"
    - label: "Xing"
      icon: "fab fa-fw fa-xing-square"
      url: "##SOCIAL_XING##"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/m-ibot"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/m-ibot"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "##SOCIAL_LINKEDIN##"
    - label: "Xing"
      icon: "fab fa-fw fa-xing-square"
      url: "##SOCIAL_XING##"
    - label: "e-Mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:##CONTACT_E_MAIL##"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_date: false
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
      toc: true
  - scope:
      path: "docs"
    values:
      sitemap: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap

readme_index:
  enabled: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs
  - .git
  - .github
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
