name: Deploy Website
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Website
        shell: bash
        env:
          REPLACE_NAME: ${{ secrets.REPLACE_NAME }}
          REPLACE_SOCIAL_XING: ${{ secrets.REPLACE_SOCIAL_XING }}
          REPLACE_SOCIAL_LINKEDIN: ${{ secrets.REPLACE_SOCIAL_LINKEDIN }}
          REPLACE_SOCIAL_GITHUB: ${{ secrets.REPLACE_SOCIAL_GITHUB }}
          REPLACE_CONTACT_E_MAIL: ${{ secrets.REPLACE_CONTACT_E_MAIL }}
          REPLACE_SEO_BING: ${{ secrets.REPLACE_SEO_BING }}
          REPLACE_DOMAIN: ${{ secrets.REPLACE_DOMAIN }}
          REPLACE_SEO_GOOGLE: ${{ secrets.REPLACE_SEO_GOOGLE }}
        run: node build.js
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
