name: "Pull Requests checks"
on:
  pull_request:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
  build-on-pullrequest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Validate HTML
        run: |
          # Simple check for placeholders or structural errors
          grep -q "##NAME##" src/index.html
